
version: 2

models:
    - name: stg_customers
      description: "Customers model"
    - name: stg_orders
      description: "Orders model"
    - name: customers
      description: "combination of customers and orders"

sources:
  - name: jaffle_shop
    description: This is a replica
    database: raw
    schema: jaffle_shop
    tables:
      - name: customers
        description: one record per customer
      - name: orders
        description: one record per order

 

